### ISSUE TITLE
Accept contributions in PowerShell?

### ISSUE THREAD

**Issue by spaelling** [Azure/ServerlessLibrary#87]
Would you accept contributions for Function App in PowerShell?

**Comment by fashaikh** [comment]
@ColbyTresness  ? I think we can add this for now .
It'll likely only appear in the "Language:All" filter and we can add a powershell dropdown item soon. Hopefully by then theres more than one powershell contribution.

**Comment by ColbyTresness** [comment]
We accept contributions for any language supported by functions - feel free to add your sample! There are improvements to the tagging system in the works which will surface this better. The fact that there aren't any languages other than JS and C# right now is simply because nobody has contributed one.
